<p align="center"><font size="6"><b>Notebook de Charles-Henri SAINT-MARS</b></font></p>

# **NumPy**

## N-dimensional array (ndarray)

Un `ndarray` (abréviation de N-dimensional array) est la structure de données principale dans la bibliothèque NumPy. C'est un tableau multidimensionnel d'éléments de même type, permettant des opérations rapides et efficaces sur des ensembles de données numériques.

Voici quelques points clés à propos des `ndarray` :

Caractéristiques d'un `ndarray` :
Dimensionnalité : Comme son nom l'indique, un `ndarray` peut avoir un nombre arbitraire de dimensions. Un tableau à 1 dimension est équivalent à une liste Python, un tableau à 2 dimensions peut être vu comme une matrice, et un tableau à N dimensions est plus général.

Homogénéité des données : Tous les éléments d'un `ndarray` sont du même type de données (par exemple, tous des entiers, des flottants, etc.). Cela permet d'optimiser les opérations et l'utilisation de la mémoire.

Attributs importants :

`ndarray.shape` : Renvoie une tuple décrivant les dimensions du tableau (nombre de lignes, colonnes, etc.). <br>
`ndarray.ndim` : Renvoie le nombre de dimensions du tableau. <br>
`ndarray.size` : Renvoie le nombre total d'éléments dans le tableau. <br>
`ndarray.dtype` : Indique le type des éléments du tableau (ex. int32, float64, etc.).

**Différence avec les listes Python :** <br>
Contrairement aux listes Python, un `ndarray` est plus performant pour des calculs mathématiques et des opérations sur de grandes quantités de données grâce à l'utilisation de types homogènes et de structures mémoire contiguës.

En résumé, un `ndarray` est une structure optimisée pour les opérations scientifiques et numériques dans Python, idéale pour manipuler des tableaux de données multidimensionnels.

In [1]:
import numpy as np

In [2]:
notre_tableau = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 , 15, 16, 17, 18, 19, 20])
print(notre_tableau) 
print(notre_tableau[3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
4


In [3]:
mon_tableau_bidimensionnel = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mon_tableau_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# La vue d'un tableau
sous_tableau = notre_tableau[0:5] # index de 0 à 4
print("sous_tableau: ", sous_tableau)
sous_tableau[0] = 10
print("sous_tableau modifié: ", sous_tableau)
print("notre_tableau modifié également: ", notre_tableau)

sous_tableau:  [1 2 3 4 5]
sous_tableau modifié:  [10  2  3  4  5]
notre_tableau modifié également:  [10  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# La copie partielle d'un tableau
notre_tableau = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 , 15, 16, 17, 18, 19, 20])
copie_sous_tableau = notre_tableau[0:5].copy()
print("copie_sous_tableau: ", copie_sous_tableau)
copie_sous_tableau[0] = 10
print("copie_sous_tableau modifié: ", copie_sous_tableau)
print("notre_tableau non modifié: ", notre_tableau)

copie_sous_tableau:  [1 2 3 4 5]
copie_sous_tableau modifié:  [10  2  3  4  5]
notre_tableau non modifié:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
# Accès à un élément d'un tableau bidimensionnel
mon_tableau_bidimensionnel[1,2] # deuxième ligne, troisième colonne
# Pour accéder à l'élément 6, on écrit mon_tableau_bidimensionnel[1,2] où 1 est l'index de la ligne et 2 est l'index de la colonne de l'élément 6.
# Le index des lignes et des colonnes comment à partir de 0.

# Deuxième manière d'accéder à un élément d'un tableau bidimensionnel
# mon_tableau_bidimensionnel[1][2]

np.int64(6)

In [7]:
# Accès à un élément d'un tableau bidimensionnel avec des indices négatifs
mon_tableau_bidimensionnel[1,-1] # deuxième ligne, dernière colonne

np.int64(6)

In [8]:
# Afficher toutes les lignes de la première colonne en utilisant le slicing
print(mon_tableau_bidimensionnel[:,0]) # : signifie toutes les lignes
# On peut voir les : comme un raccourci pour dire "du début jusqu'à la fin de l'ensemble des lignes".

[1 4 7]


In [9]:
# Afficher toutes les colonnes de la deuxième ligne en utilisant le slicing
print(mon_tableau_bidimensionnel[1,:]) # : signifie toutes les colonnes

[4 5 6]


In [10]:
# Afficher toutes les lignes d'une part et les colonnes avec un pas de 2 d'autre part
print(mon_tableau_bidimensionnel[::,::2])


[[1 3]
 [4 6]
 [7 9]]


In [11]:
# Afficher toutes lignes de la dernière colonne en utilisant un index négatif
print(mon_tableau_bidimensionnel[:,-1])

[3 6 9]


In [12]:
print(mon_tableau_bidimensionnel[:,1:-1]) # toutes les lignes, de la deuxième colonne à l'avant dernière colonne
# -1 est l'index de la fin dans le slicing donc il est exclusif. Cela revient à désigner l'avant dernière colonne (index -2).

[[2]
 [5]
 [8]]


In [13]:
# Afficher la dernière ligne et la deuxième colonne en utilisant le slicing
print(mon_tableau_bidimensionnel[-1,1:-1])

# Deuxième manière d'accéder à la dernière ligne et la deuxième colonne
print(mon_tableau_bidimensionnel[-1,1:2])

[8]
[8]


In [14]:
# Créer une matrice de 6 x 4 avec des nombres aléatoires à l'aide de la fonction randint() de numpy.
# Les valeurs vont de 0 à 100 (0 est inclusif et 100 est exclusif).
matrice = np.random.randint(0, 100, (6, 4))
print(matrice)

[[69 71 10 84]
 [70 17 40 65]
 [13 59 45 98]
 [71 44 30 57]
 [36 85 61 21]
 [36 92 10 79]]


### Les attribut d'un ndarray (N-dimensional array)

In [15]:
matrice.ndim # nombre de dimensions

2

In [16]:
matrice.shape # forme de la matrice

(6, 4)

In [17]:
matrice.dtype # type des éléments de la matrice

dtype('int32')

In [18]:
matrice.size # nombre total d'éléments dans la matrice

24

In [19]:
matrice[matrice > 50] # sélectionner les éléments de la matrice qui sont supérieurs à 50

array([69, 71, 84, 70, 65, 59, 98, 71, 57, 85, 61, 92, 79], dtype=int32)

In [20]:
matrice > 50 # renvoie un tableau de booléens

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

Ce qui est True pour matrice > 50 est affiché et ce qui est False n'est pas affiché

In [21]:
matrice[(matrice >= 50) & (matrice <= 70)] # sélectionner les éléments de la matrice qui sont supérieurs ou égaux à 50 et inférieurs ou égaux à 70

array([69, 70, 65, 59, 57, 61], dtype=int32)

In [22]:
matrice[(matrice >=50 ) | (matrice <= 30)]  # sélectionner les éléments de la matrice qui sont supérieurs ou égaux à 50 ou inférieurs ou égaux à 30

array([69, 71, 10, 84, 70, 17, 65, 13, 59, 98, 71, 30, 57, 85, 61, 21, 92,
       10, 79], dtype=int32)

In [23]:
# Concaténation de tableaux
tableau1 = np.array([[1, 2, 3], [4, 5, 6]])
tableau2 = np.array([[7, 8, 9], [10, 11, 12]])
tableau3 = np.concatenate([tableau1, tableau2], axis=0) # concaténation verticale
print(tableau3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# Concaténation horizontale de tableaux
tableau4 = np.concatenate([tableau1, tableau2], axis=1) # concaténation horizontale
print(tableau4)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [25]:
# Concaténation de tableaux de dimensions différentes
tableau5 = np.array([1, 2, 3])
tableau6 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
tableau7 = np.vstack([tableau5, tableau6]) # concaténation verticale
print(tableau7)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Concaténation horizontale de tableaux de dimensions différentes
tableau8 = np.hstack([tableau6, tableau5.reshape(3,1)]) # concaténation horizontale
print(tableau8)

[[ 4  5  6  1]
 [ 7  8  9  2]
 [10 11 12  3]]


In [27]:
 # Créer un tableau de 10 éléments
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
len(array) # longueur du tableau : 10
array1, array2, array3 = np.split(array, [2, 6]) # découper le tableau en trois parties
# 2 est l'index du début de la première découpe et 6 est l'index du début de la deuxième découpe.
print(array1, array2, array3)

[1 2] [3 4 5 6] [ 7  8  9 10]


In [28]:
# Créer un tableau bidimensionnel
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# Axes de découpe
# axis = 0 # axe des index des lignes (dit aussi vertical car les index des lignes sont sur l'axe vertical)
# axis = 1 # axe des index des colonnes (dit aussi horizontal car les index des colonnes sont sur l'axe horizontal)

In [30]:
# Découper le tableau en deux parties selon l'axe 0 (vertical)
array1, array2 = np.vsplit(array, [2]) # [2] est l'index de la première ligne de la deuxième partie
print("array1 : ")
print(array1)
print("")
print("array2 : ")
print(array2)

array1 : 
[[1 2 3 4]
 [5 6 7 8]]

array2 : 
[[ 9 10 11 12]]


In [31]:
# Découper le tableau en deux parties selon l'axe 1 (horizontal)
array1, array2 = np.hsplit(array, [2]) # [2] est l'index de la première colonne de la deuxième partie
print("array1 : ")
print(array1)
print("")
print("array2 : ")
print(array2)

array1 : 
[[ 1  2]
 [ 5  6]
 [ 9 10]]

array2 : 
[[ 3  4]
 [ 7  8]
 [11 12]]


### Opérations arithmétiques sur les tableaux

In [32]:
 # Créer tableau aléatoire de 10 lignes et 9 colonnes avec des valeurs comprises entre 0 et 350 (avec 350 exclus)
array = np.random.randint(350, size=(10, 9))
print(array)

[[176 235 280  93  10 289 119 193 299]
 [317   1 171 188 265  58 248 292  99]
 [244   0 200 171  29 197 122  19 240]
 [122  95 148 307 194  21 151 151 136]
 [123 207  60 272 101 213 277  56 348]
 [134  44 287 113 173 321 216 347 280]
 [100 331 123 261 288 168 344 293 265]
 [ 95 259   0  56  29 161  92 316 133]
 [331 109 108  66  84 246 136  10  39]
 [ 45  45 133 153 175 191 185  48 141]]


In [33]:
array + 2 # ajouter 2 à chaque élément du tableau

array([[178, 237, 282,  95,  12, 291, 121, 195, 301],
       [319,   3, 173, 190, 267,  60, 250, 294, 101],
       [246,   2, 202, 173,  31, 199, 124,  21, 242],
       [124,  97, 150, 309, 196,  23, 153, 153, 138],
       [125, 209,  62, 274, 103, 215, 279,  58, 350],
       [136,  46, 289, 115, 175, 323, 218, 349, 282],
       [102, 333, 125, 263, 290, 170, 346, 295, 267],
       [ 97, 261,   2,  58,  31, 163,  94, 318, 135],
       [333, 111, 110,  68,  86, 248, 138,  12,  41],
       [ 47,  47, 135, 155, 177, 193, 187,  50, 143]], dtype=int32)

In [34]:
print(array)

[[176 235 280  93  10 289 119 193 299]
 [317   1 171 188 265  58 248 292  99]
 [244   0 200 171  29 197 122  19 240]
 [122  95 148 307 194  21 151 151 136]
 [123 207  60 272 101 213 277  56 348]
 [134  44 287 113 173 321 216 347 280]
 [100 331 123 261 288 168 344 293 265]
 [ 95 259   0  56  29 161  92 316 133]
 [331 109 108  66  84 246 136  10  39]
 [ 45  45 133 153 175 191 185  48 141]]


In [35]:
array - 2 # soustraire 2 à chaque élément du tableau

array([[174, 233, 278,  91,   8, 287, 117, 191, 297],
       [315,  -1, 169, 186, 263,  56, 246, 290,  97],
       [242,  -2, 198, 169,  27, 195, 120,  17, 238],
       [120,  93, 146, 305, 192,  19, 149, 149, 134],
       [121, 205,  58, 270,  99, 211, 275,  54, 346],
       [132,  42, 285, 111, 171, 319, 214, 345, 278],
       [ 98, 329, 121, 259, 286, 166, 342, 291, 263],
       [ 93, 257,  -2,  54,  27, 159,  90, 314, 131],
       [329, 107, 106,  64,  82, 244, 134,   8,  37],
       [ 43,  43, 131, 151, 173, 189, 183,  46, 139]], dtype=int32)

In [36]:
array * 2 # multiplier chaque élément du tableau par 2 

array([[352, 470, 560, 186,  20, 578, 238, 386, 598],
       [634,   2, 342, 376, 530, 116, 496, 584, 198],
       [488,   0, 400, 342,  58, 394, 244,  38, 480],
       [244, 190, 296, 614, 388,  42, 302, 302, 272],
       [246, 414, 120, 544, 202, 426, 554, 112, 696],
       [268,  88, 574, 226, 346, 642, 432, 694, 560],
       [200, 662, 246, 522, 576, 336, 688, 586, 530],
       [190, 518,   0, 112,  58, 322, 184, 632, 266],
       [662, 218, 216, 132, 168, 492, 272,  20,  78],
       [ 90,  90, 266, 306, 350, 382, 370,  96, 282]], dtype=int32)

In [37]:
array[:,0] * 10 # multiplier la première colonne par 10

array([1760, 3170, 2440, 1220, 1230, 1340, 1000,  950, 3310,  450],
      dtype=int32)

In [38]:
print(array)

[[176 235 280  93  10 289 119 193 299]
 [317   1 171 188 265  58 248 292  99]
 [244   0 200 171  29 197 122  19 240]
 [122  95 148 307 194  21 151 151 136]
 [123 207  60 272 101 213 277  56 348]
 [134  44 287 113 173 321 216 347 280]
 [100 331 123 261 288 168 344 293 265]
 [ 95 259   0  56  29 161  92 316 133]
 [331 109 108  66  84 246 136  10  39]
 [ 45  45 133 153 175 191 185  48 141]]


In [39]:
array / 2 # diviser chaque élément du tableau par 2

array([[ 88. , 117.5, 140. ,  46.5,   5. , 144.5,  59.5,  96.5, 149.5],
       [158.5,   0.5,  85.5,  94. , 132.5,  29. , 124. , 146. ,  49.5],
       [122. ,   0. , 100. ,  85.5,  14.5,  98.5,  61. ,   9.5, 120. ],
       [ 61. ,  47.5,  74. , 153.5,  97. ,  10.5,  75.5,  75.5,  68. ],
       [ 61.5, 103.5,  30. , 136. ,  50.5, 106.5, 138.5,  28. , 174. ],
       [ 67. ,  22. , 143.5,  56.5,  86.5, 160.5, 108. , 173.5, 140. ],
       [ 50. , 165.5,  61.5, 130.5, 144. ,  84. , 172. , 146.5, 132.5],
       [ 47.5, 129.5,   0. ,  28. ,  14.5,  80.5,  46. , 158. ,  66.5],
       [165.5,  54.5,  54. ,  33. ,  42. , 123. ,  68. ,   5. ,  19.5],
       [ 22.5,  22.5,  66.5,  76.5,  87.5,  95.5,  92.5,  24. ,  70.5]])

### Les méthodes de Numpy pour les opérations arithmétiques

In [40]:
# Ajouter 2 à chaque élément du tableau en utilisant la méthode add() de numpy
np.add(array, 2) 

array([[178, 237, 282,  95,  12, 291, 121, 195, 301],
       [319,   3, 173, 190, 267,  60, 250, 294, 101],
       [246,   2, 202, 173,  31, 199, 124,  21, 242],
       [124,  97, 150, 309, 196,  23, 153, 153, 138],
       [125, 209,  62, 274, 103, 215, 279,  58, 350],
       [136,  46, 289, 115, 175, 323, 218, 349, 282],
       [102, 333, 125, 263, 290, 170, 346, 295, 267],
       [ 97, 261,   2,  58,  31, 163,  94, 318, 135],
       [333, 111, 110,  68,  86, 248, 138,  12,  41],
       [ 47,  47, 135, 155, 177, 193, 187,  50, 143]], dtype=int32)

In [41]:
# Retrancher 2 à chaque élément du tableau en utilisant la méthode subtract() de numpy
np.subtract(array, 2)

array([[174, 233, 278,  91,   8, 287, 117, 191, 297],
       [315,  -1, 169, 186, 263,  56, 246, 290,  97],
       [242,  -2, 198, 169,  27, 195, 120,  17, 238],
       [120,  93, 146, 305, 192,  19, 149, 149, 134],
       [121, 205,  58, 270,  99, 211, 275,  54, 346],
       [132,  42, 285, 111, 171, 319, 214, 345, 278],
       [ 98, 329, 121, 259, 286, 166, 342, 291, 263],
       [ 93, 257,  -2,  54,  27, 159,  90, 314, 131],
       [329, 107, 106,  64,  82, 244, 134,   8,  37],
       [ 43,  43, 131, 151, 173, 189, 183,  46, 139]], dtype=int32)

In [42]:
# Multiplier par 2 chaque élément du tableau en utilisant la méthode multiply() de numpy
np.multiply(array, 2)

array([[352, 470, 560, 186,  20, 578, 238, 386, 598],
       [634,   2, 342, 376, 530, 116, 496, 584, 198],
       [488,   0, 400, 342,  58, 394, 244,  38, 480],
       [244, 190, 296, 614, 388,  42, 302, 302, 272],
       [246, 414, 120, 544, 202, 426, 554, 112, 696],
       [268,  88, 574, 226, 346, 642, 432, 694, 560],
       [200, 662, 246, 522, 576, 336, 688, 586, 530],
       [190, 518,   0, 112,  58, 322, 184, 632, 266],
       [662, 218, 216, 132, 168, 492, 272,  20,  78],
       [ 90,  90, 266, 306, 350, 382, 370,  96, 282]], dtype=int32)

In [43]:
# Diviser par 2 chaque élément du tableau en utilisant la méthode divide() de numpy
np.divide(array, 2)

array([[ 88. , 117.5, 140. ,  46.5,   5. , 144.5,  59.5,  96.5, 149.5],
       [158.5,   0.5,  85.5,  94. , 132.5,  29. , 124. , 146. ,  49.5],
       [122. ,   0. , 100. ,  85.5,  14.5,  98.5,  61. ,   9.5, 120. ],
       [ 61. ,  47.5,  74. , 153.5,  97. ,  10.5,  75.5,  75.5,  68. ],
       [ 61.5, 103.5,  30. , 136. ,  50.5, 106.5, 138.5,  28. , 174. ],
       [ 67. ,  22. , 143.5,  56.5,  86.5, 160.5, 108. , 173.5, 140. ],
       [ 50. , 165.5,  61.5, 130.5, 144. ,  84. , 172. , 146.5, 132.5],
       [ 47.5, 129.5,   0. ,  28. ,  14.5,  80.5,  46. , 158. ,  66.5],
       [165.5,  54.5,  54. ,  33. ,  42. , 123. ,  68. ,   5. ,  19.5],
       [ 22.5,  22.5,  66.5,  76.5,  87.5,  95.5,  92.5,  24. ,  70.5]])

### Les méthodes de Numpy pour les calculs statistiques

In [44]:
print(np.mean(array)) # moyenne des éléments du tableau
print(array.mean()) # moyenne des éléments du tableau

166.7888888888889
166.7888888888889


In [45]:
# Calculer la moyenne par colonne
print(np.mean(array, axis=0))

[168.7 132.6 151.  168.  134.8 186.5 189.  172.5 198. ]


In [46]:
# Calculer la moyenne par ligne
print(np.mean(array, axis=1))

[188.22222222 182.11111111 135.77777778 147.22222222 184.11111111
 212.77777778 241.44444444 126.77777778 125.44444444 124.        ]


In [47]:
print(np.median(array)) # médiane des éléments du tableau

157.0


In [48]:
print(np.std(array)) # écart-type des éléments du tableau

98.46256981371646


In [49]:
print(np.sum(array)) # somme des éléments du tableau

15011


In [50]:
print(array.min()) # élément minimum du tableau
print(array.max()) # élément maximum du tableau

0
348


In [51]:
# Calculer la variance des éléments du tableau
print(np.var(array))

9694.877654320988


In [52]:
np.sqrt(np.var(array)) # écart-type des éléments du tableau (racine carrée de la variance)

np.float64(98.46256981371646)

In [53]:
print(np.percentile(array, 25)) # premier quartile des éléments du tableau

95.0


In [54]:
print(np.percentile(array, 50)) # deuxième quartile des éléments du tableau (médiane)

157.0


In [55]:
print(np.percentile(array, 75)) # troisième quartile des éléments du tableau

256.25


In [56]:
print(np.percentile(array, 90)) # neuvième décile des éléments du tableau

299.80000000000007


## <font color="red">Problème à résoudre de la capsule 41</font>

**Objectif : Manipuler un array contenant les prix de vente de 20 maisons vendues en 2008 dans une petite ville du Midwest**
1. Importer les données au format array à partir du fichier houses.csv
2. Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 euros
3. Convertir les pieds carrés en mètres carrés, sachant que 1 pied carré = 0.09 m². 
4. Combien de maisons ont un terrain de plus de 1000 m²?
5. Calculer la somme totale obtenue après la vente des 20 maisons.
6. Quelle est la taille de la maison vendue la plus chère ?
7. Juste pour l’exercice, splitter (casser) l’array en trois tableaux, puis les concaténer à nouveau pour obtenir le tableau initial.

In [57]:
# 1. importation du fichier csv
houses = np.genfromtxt('Houses.csv', delimiter=',', dtype=int)
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding=None, *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return 

In [58]:
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [59]:
dir(houses)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '_

In [60]:
houses.shape # forme de la matrice (nombre de lignes, nombre de colonnes)

(20, 3)

In [61]:
# La première colonne représente le prix de vente des maisons en dollars
# La deuxième colonne représente la surface de la maison en pieds carrés
# La troisième colonne représente la surface du terrain en pieds carrés
# 1 dolar = 0.86 euros
# 1 pied carré = 0.09 mètre carré


In [62]:
# 2. Convertir les prix des maisons en euros
houses[:,0] = houses[:,0] * 0.86
print(houses)

[[182320   4148  25264]
 [197800   2501  11891]
 [291540   4374  25351]
 [248540   2398  22215]
 [137600   2536   9234]
 [ 73100   2368  13329]
 [ 73100   1264   8407]
 [124700   1572  12588]
 [141040   2375  16204]
 [106210   1161   9626]
 [154800   1542   8755]
 [137170   1464  14636]
 [134160   2240  21780]
 [125990   1269  11250]
 [ 87290    924   7361]
 [ 94428    768  10497]
 [156520   1320  15768]
 [ 94600   1845  12153]
 [107500   1274  13634]
 [ 68800   1905  10890]]


In [63]:
# 3. Convertir les pieds carrés en mètres carrés, sachant que 1 pied carré = 0.09 m². 
houses[:,1] = houses[:,1] * 0.09
houses[:,2] = houses[:,2] * 0.09
print(houses)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [64]:
# 4. Combien de maisons ont un terrain de plus de 1000 m² ?
terrains_plus_1000m2 = houses[houses[:,2] > 1000] # houses[surface_terrain > 1000]
print(terrains_plus_1000m2)
resultat = len(terrains_plus_1000m2) # nombre de listes imbriquées c-à-d le nombre de maisons
print("Le nombre de maisons qui ont un terrain de plus de 1000 m² est : ", resultat)


[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [ 73100    213   1199]
 [124700    141   1132]
 [141040    213   1458]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]]
Le nombre de maisons qui ont un terrain de plus de 1000 m² est :  13


In [65]:
# 5. Calculer la somme totale obtenue après la vente des 20 maisons.
somme_totale = np.sum(houses[:,0])
print("La somme totale obtenue après la vente des 20 maisons est : ", somme_totale, "euros")

La somme totale obtenue après la vente des 20 maisons est :  2737208 euros


In [66]:
# 6. Quelle est la taille de la maison vendue la plus chère ?
taille_maison_plus_chere = np.max(houses[:,1])
print("La taille de la maison vendue la plus chère est : ", taille_maison_plus_chere, "m²")


La taille de la maison vendue la plus chère est :  393 m²


In [67]:
# Corrigé de la question précédente à savoir, 
# Quelle est la taille de la maison vendue la plus chère ?
index_prix_max = np.argmax(houses[:,0])
print("Index de la maison vendue la plus chère : ", index_prix_max)
taille_maison_plus_chere = houses[index_prix_max, 1]
print("La taille de la maison vendue la plus chère est : ", taille_maison_plus_chere, "m²")



Index de la maison vendue la plus chère :  2
La taille de la maison vendue la plus chère est :  393 m²


In [68]:
# 7. Splitter (casser) houses en trois tableaux selon l'axe 0
array1, array2, array3 = np.vsplit(houses, [6, 12]) # [6, 12] sont les index des premières lignes des deuxième et troisième parties
print("array1 : \n",array1) 
print("array2 : \n",array2)
print("array3 : \n",array3)


array1 : 
 [[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]]
array2 : 
 [[ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]]
array3 : 
 [[134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [69]:
# Concaténer array1, array2 et array3 à nouveau pour obtenir le tableau initial selon l'axe 0
houses_original = np.concatenate([array1, array2, array3], axis=0) # concaténation selon l'axe 0 (vertical)
print("houses_original : \n", houses_original)

houses_original : 
 [[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]
